package com.wallxu.seckill.dao.domain;

import java.io.Serializable;

public class TbMiaoshaOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_order.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_order.user_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_order.order_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_order.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_order.id
     *
     * @return the value of tb_miaosha_order.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_order.id
     *
     * @param id the value for tb_miaosha_order.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_order.user_id
     *
     * @return the value of tb_miaosha_order.user_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_order.user_id
     *
     * @param userId the value for tb_miaosha_order.user_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_order.order_id
     *
     * @return the value of tb_miaosha_order.order_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_order.order_id
     *
     * @param orderId the value for tb_miaosha_order.order_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_order.goods_id
     *
     * @return the value of tb_miaosha_order.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_order.goods_id
     *
     * @param goodsId the value for tb_miaosha_order.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orderId=").append(orderId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbMiaoshaOrder other = (TbMiaoshaOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        return result;
    }
}