package com.wallxu.seckill.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TbMiaoshaGood implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_good.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_good.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_good.miaosha_price
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private BigDecimal miaoshaPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_good.stock_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_good.start_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_good.end_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_good.id
     *
     * @return the value of tb_miaosha_good.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_good.id
     *
     * @param id the value for tb_miaosha_good.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_good.goods_id
     *
     * @return the value of tb_miaosha_good.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_good.goods_id
     *
     * @param goodsId the value for tb_miaosha_good.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_good.miaosha_price
     *
     * @return the value of tb_miaosha_good.miaosha_price
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public BigDecimal getMiaoshaPrice() {
        return miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_good.miaosha_price
     *
     * @param miaoshaPrice the value for tb_miaosha_good.miaosha_price
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setMiaoshaPrice(BigDecimal miaoshaPrice) {
        this.miaoshaPrice = miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_good.stock_count
     *
     * @return the value of tb_miaosha_good.stock_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_good.stock_count
     *
     * @param stockCount the value for tb_miaosha_good.stock_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_good.start_date
     *
     * @return the value of tb_miaosha_good.start_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_good.start_date
     *
     * @param startDate the value for tb_miaosha_good.start_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_good.end_date
     *
     * @return the value of tb_miaosha_good.end_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_good.end_date
     *
     * @param endDate the value for tb_miaosha_good.end_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", miaoshaPrice=").append(miaoshaPrice);
        sb.append(", stockCount=").append(stockCount);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbMiaoshaGood other = (TbMiaoshaGood) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getMiaoshaPrice() == null ? other.getMiaoshaPrice() == null : this.getMiaoshaPrice().equals(other.getMiaoshaPrice()))
            && (this.getStockCount() == null ? other.getStockCount() == null : this.getStockCount().equals(other.getStockCount()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getMiaoshaPrice() == null) ? 0 : getMiaoshaPrice().hashCode());
        result = prime * result + ((getStockCount() == null) ? 0 : getStockCount().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        return result;
    }
}