package com.wallxu.seckill.dao.domain;

import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

public class TbMiaoshaUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long id;


    @NotNull(message = "{user.mobile.notNull}")
    @Length(min = 11, max = 11, message = "{user.mobile.length}")
    private String mobile;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.nickname
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.password
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @NotNull(message = "{user.password.notNull}")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.salt
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.head
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.register_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.last_login_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Date lastLoginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_miaosha_user.login_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.id
     *
     * @return the value of tb_miaosha_user.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.id
     *
     * @param id the value for tb_miaosha_user.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.nickname
     *
     * @return the value of tb_miaosha_user.nickname
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.nickname
     *
     * @param nickname the value for tb_miaosha_user.nickname
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.password
     *
     * @return the value of tb_miaosha_user.password
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.password
     *
     * @param password the value for tb_miaosha_user.password
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.salt
     *
     * @return the value of tb_miaosha_user.salt
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.salt
     *
     * @param salt the value for tb_miaosha_user.salt
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.head
     *
     * @return the value of tb_miaosha_user.head
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.head
     *
     * @param head the value for tb_miaosha_user.head
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.register_date
     *
     * @return the value of tb_miaosha_user.register_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.register_date
     *
     * @param registerDate the value for tb_miaosha_user.register_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.last_login_date
     *
     * @return the value of tb_miaosha_user.last_login_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.last_login_date
     *
     * @param lastLoginDate the value for tb_miaosha_user.last_login_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_miaosha_user.login_count
     *
     * @return the value of tb_miaosha_user.login_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_miaosha_user.login_count
     *
     * @param loginCount the value for tb_miaosha_user.login_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", nickname=").append(nickname);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", head=").append(head);
        sb.append(", registerDate=").append(registerDate);
        sb.append(", lastLoginDate=").append(lastLoginDate);
        sb.append(", loginCount=").append(loginCount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbMiaoshaUser other = (TbMiaoshaUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getHead() == null ? other.getHead() == null : this.getHead().equals(other.getHead()))
            && (this.getRegisterDate() == null ? other.getRegisterDate() == null : this.getRegisterDate().equals(other.getRegisterDate()))
            && (this.getLastLoginDate() == null ? other.getLastLoginDate() == null : this.getLastLoginDate().equals(other.getLastLoginDate()))
            && (this.getLoginCount() == null ? other.getLoginCount() == null : this.getLoginCount().equals(other.getLoginCount()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getHead() == null) ? 0 : getHead().hashCode());
        result = prime * result + ((getRegisterDate() == null) ? 0 : getRegisterDate().hashCode());
        result = prime * result + ((getLastLoginDate() == null) ? 0 : getLastLoginDate().hashCode());
        result = prime * result + ((getLoginCount() == null) ? 0 : getLoginCount().hashCode());
        return result;
    }
}