package com.wallxu.seckill.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TbOrderInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.user_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.delivery_add_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Long deliveryAddId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.goods_name
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.goods_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.goods_price
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.order_channel
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Byte orderChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.status
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.create_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_info.pay_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private Date payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.id
     *
     * @return the value of tb_order_info.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.id
     *
     * @param id the value for tb_order_info.id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.user_id
     *
     * @return the value of tb_order_info.user_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.user_id
     *
     * @param userId the value for tb_order_info.user_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.goods_id
     *
     * @return the value of tb_order_info.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.goods_id
     *
     * @param goodsId the value for tb_order_info.goods_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.delivery_add_id
     *
     * @return the value of tb_order_info.delivery_add_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Long getDeliveryAddId() {
        return deliveryAddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.delivery_add_id
     *
     * @param deliveryAddId the value for tb_order_info.delivery_add_id
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setDeliveryAddId(Long deliveryAddId) {
        this.deliveryAddId = deliveryAddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.goods_name
     *
     * @return the value of tb_order_info.goods_name
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.goods_name
     *
     * @param goodsName the value for tb_order_info.goods_name
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.goods_count
     *
     * @return the value of tb_order_info.goods_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.goods_count
     *
     * @param goodsCount the value for tb_order_info.goods_count
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.goods_price
     *
     * @return the value of tb_order_info.goods_price
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.goods_price
     *
     * @param goodsPrice the value for tb_order_info.goods_price
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.order_channel
     *
     * @return the value of tb_order_info.order_channel
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Byte getOrderChannel() {
        return orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.order_channel
     *
     * @param orderChannel the value for tb_order_info.order_channel
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setOrderChannel(Byte orderChannel) {
        this.orderChannel = orderChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.status
     *
     * @return the value of tb_order_info.status
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.status
     *
     * @param status the value for tb_order_info.status
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.create_date
     *
     * @return the value of tb_order_info.create_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.create_date
     *
     * @param createDate the value for tb_order_info.create_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_info.pay_date
     *
     * @return the value of tb_order_info.pay_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_info.pay_date
     *
     * @param payDate the value for tb_order_info.pay_date
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", deliveryAddId=").append(deliveryAddId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", goodsCount=").append(goodsCount);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append(", orderChannel=").append(orderChannel);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", payDate=").append(payDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbOrderInfo other = (TbOrderInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getDeliveryAddId() == null ? other.getDeliveryAddId() == null : this.getDeliveryAddId().equals(other.getDeliveryAddId()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getGoodsCount() == null ? other.getGoodsCount() == null : this.getGoodsCount().equals(other.getGoodsCount()))
            && (this.getGoodsPrice() == null ? other.getGoodsPrice() == null : this.getGoodsPrice().equals(other.getGoodsPrice()))
            && (this.getOrderChannel() == null ? other.getOrderChannel() == null : this.getOrderChannel().equals(other.getOrderChannel()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getPayDate() == null ? other.getPayDate() == null : this.getPayDate().equals(other.getPayDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getDeliveryAddId() == null) ? 0 : getDeliveryAddId().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getGoodsCount() == null) ? 0 : getGoodsCount().hashCode());
        result = prime * result + ((getGoodsPrice() == null) ? 0 : getGoodsPrice().hashCode());
        result = prime * result + ((getOrderChannel() == null) ? 0 : getOrderChannel().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getPayDate() == null) ? 0 : getPayDate().hashCode());
        return result;
    }
}