server:
  port: 8008
  servlet:
    context-path: /financeWeb

spring:
  datasource:
    url: jdbc:mysql:///wallxu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  application:
    name: finance-web

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

