server:
  port: 8082


spring:
  application:
    name: eureka-client



eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://xufeng01:8081/eureka/,http://xufeng02:8082/eureka/
  instance:
    hostname : xufeng02