package com.wallxu.seckill.dao.mapper;

import com.wallxu.seckill.dao.domain.TbMiaoshaUser;
import com.wallxu.seckill.dao.domain.TbMiaoshaUserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TbMiaoshaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    long countByExample(TbMiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByExample(TbMiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insert(TbMiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insertSelective(TbMiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    List<TbMiaoshaUser> selectByExample(TbMiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    TbMiaoshaUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbMiaoshaUser record, @Param("example") TbMiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExample(@Param("record") TbMiaoshaUser record, @Param("example") TbMiaoshaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKeySelective(TbMiaoshaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_user
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKey(TbMiaoshaUser record);
}