package com.wallxu.seckill.dao.mapper;

import com.wallxu.seckill.dao.domain.TbGoodsVo;
import com.wallxu.seckill.dao.domain.TbMiaoshaGood;
import com.wallxu.seckill.dao.domain.TbMiaoshaGoodExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper
public interface TbMiaoshaGoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    long countByExample(TbMiaoshaGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByExample(TbMiaoshaGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insert(TbMiaoshaGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insertSelective(TbMiaoshaGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    List<TbMiaoshaGood> selectByExample(TbMiaoshaGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    TbMiaoshaGood selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbMiaoshaGood record, @Param("example") TbMiaoshaGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExample(@Param("record") TbMiaoshaGood record, @Param("example") TbMiaoshaGoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKeySelective(TbMiaoshaGood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_good
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKey(TbMiaoshaGood record);

    //所有秒杀商品
    @Select("SELECT mg.miaosha_price, mg.stock_count, g.* from tb_miaosha_good mg, tb_goods g where mg.goods_id = g.id ")
    List<TbGoodsVo> getMiaoshaGoods();

    //某个秒杀商品详情
    @Select("SELECT mg.miaosha_price, mg.stock_count, mg.start_date, mg.end_date , g.* from tb_miaosha_good mg, tb_goods g where mg.goods_id = g.id and g.id = #{goodsId}")
    TbGoodsVo getMiaoshaGoodsDetail(Long goodsId);

    @Update("update tb_miaosha_good set stock_count = stock_count - 1 where goods_id = #{goodsId} and stock_count > 0")
    int reduceNum(long goodsId);
}