package com.wallxu.seckill.dao.mapper;

import com.wallxu.seckill.dao.domain.TbMiaoshaOrder;
import com.wallxu.seckill.dao.domain.TbMiaoshaOrderExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TbMiaoshaOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    long countByExample(TbMiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByExample(TbMiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insert(TbMiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insertSelective(TbMiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    List<TbMiaoshaOrder> selectByExample(TbMiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    TbMiaoshaOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbMiaoshaOrder record, @Param("example") TbMiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExample(@Param("record") TbMiaoshaOrder record, @Param("example") TbMiaoshaOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKeySelective(TbMiaoshaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_miaosha_order
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKey(TbMiaoshaOrder record);
}