package com.wallxu.seckill.dao.mapper;

import com.wallxu.seckill.dao.domain.TbOrderInfo;
import com.wallxu.seckill.dao.domain.TbOrderInfoExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface TbOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    long countByExample(TbOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByExample(TbOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insert(TbOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int insertSelective(TbOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    List<TbOrderInfo> selectByExample(TbOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    TbOrderInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbOrderInfo record, @Param("example") TbOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByExample(@Param("record") TbOrderInfo record, @Param("example") TbOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKeySelective(TbOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbg.generated Sun Jul 15 17:31:25 CST 2018
     */
    int updateByPrimaryKey(TbOrderInfo record);


    @Insert("INSERT INTO `tb_order_info` (`id`,`user_id`, `goods_id`, `delivery_add_id`, `goods_name`, `goods_count`, `goods_price`,\n" +
            " `order_channel`, `status`, `create_date`)\n" +
            " SELECT #{orderId}, #{userId}, id, 1, goods_name, 1, goods_price, 1, 0, CURRENT_TIMESTAMP from tb_goods where id = #{goodsId}")
//    @Options(useGeneratedKeys = true)
//    @SelectKey(keyColumn = "id", keyProperty = "id", resultType = long.class, before = false, statement = "select last_insert_id() ")
    int createOrder(@Param(value = "userId") long userId, @Param(value = "goodsId") long goodsId, @Param(value = "orderId") long orderId);
}