server:
  port: 8089
  servlet:
    context-path: /sell
    
    
spring:
  datasource:
    url: jdbc:mysql:///wallxu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  # FREEMARKER (FreeMarkerProperties)
  freemarker:
    charset: utf-8
    suffix: .ftl
    template-loader-path: classpath:/templates/


  jackson:
    default-property-inclusion: non_null

